spring.application.name=HotelReservationSystem
server.port=8080

# MySQL Database Configuration (Port 3307)
spring.datasource.url=jdbc:mysql://localhost:3307/hotel_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Rules
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway Database Migration Core Configurations
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

# JWT Secret Configuration
app.jwt.secret=lUYSxcvEf3S3PgVYq5fEk4xxuVeBdHVY
app.jwt.expiration-ms=86400000

# Session Cookie Configuration (Expires when browser closes)
server.servlet.session.cookie.max-age=-1

#Redis connection Settings
spring.data.redis.host=localhost
spring.data.redis.port=6380

#cache configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=10m

#Prevents caching null values if a hotel/rate doesnt eixst
spring.cache.redis.cache-null-values=false

# Keycloak OIDC Provider Properties
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/hotel-app
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/hotel-realm/protocol/openid-connect/certs

# OAuth2 Client Setup (REQUIRED for Thymeleaf Browser Login Redirection)
spring.security.oauth2.client.registration.keycloak.client-id=hotel-app
spring.security.oauth2.client.registration.keycloak.client-secret=lUYSxcvEf3S3PgVYq5fEk4xxuVeBdHVY
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/hotel-app



