server:
  port: 8082

spring:
  application:
    name: inventory-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/hotel-realm

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/hotel_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data-hotel.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/